shortener:
    port: "8080"
    alphabet: "abs"
    length: 10
storage:
    type: "postgres"
    host: "localhost"
    port: "5432"
    database_name: "compressor"
    user: "postgres"
    password: "password"
migrations:
    migrations_path: "../../../../migrations/changesets"
