openapi: 3.0.0
info:
  title: Compressor API
  version: 1.0.0
  contact:
    name: Ivan
    url: https://github.com/AFK068
paths:
  /url:
    get:
      summary: Get original URL by short URL
      parameters:
        - name: short-url
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Url successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
    post:
      summary: Post original URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
      responses:
        '200':
          description: Url successfully saved
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrl:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'      
          
components:
  schemas:
    ApiErrorResponse:
      type: object
      properties:
        description:
          type: string
        code:
          type: string
        exceptionName:
          type: string
        exceptionMessage:
          type: string